{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kt.gigagenie",
    "module": "geniesdk",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "geniesdk-0.1.aar",
          "url": "geniesdk-0.1.aar",
          "size": 81801,
          "sha512": "b4b9ebe233fe37728a63ea78450c77db3b4dfe24654759ea403d94b5db6b22ee5b8d96576a0fa6bff3b7dbef73f8fb236d8827bb6c9aa5eb74bff74cf9a614f2",
          "sha256": "99fcaca17a4979203921c9ab700d4a5362935db9669dbf58bdbb67e7834c4454",
          "sha1": "240e292fa6e8613293fde71405a7e38504741872",
          "md5": "81a33aaca8db0a4d523a8acf31a81995"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "geniesdk-0.1.aar",
          "url": "geniesdk-0.1.aar",
          "size": 81801,
          "sha512": "b4b9ebe233fe37728a63ea78450c77db3b4dfe24654759ea403d94b5db6b22ee5b8d96576a0fa6bff3b7dbef73f8fb236d8827bb6c9aa5eb74bff74cf9a614f2",
          "sha256": "99fcaca17a4979203921c9ab700d4a5362935db9669dbf58bdbb67e7834c4454",
          "sha1": "240e292fa6e8613293fde71405a7e38504741872",
          "md5": "81a33aaca8db0a4d523a8acf31a81995"
        }
      ]
    }
  ]
}
