{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kt.gigagenie",
    "module": "geniesdk",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "geniesdk-1.1.1.aar",
          "url": "geniesdk-1.1.1.aar",
          "size": 92144,
          "sha512": "2dc09e21e13ab10780f93327b8500997796108fc32a53ebe6ecc7356a962e2d4527c23501d93dfc27a00fafd7edfd52e5d3eb3359f6ac0c4207b077fb13e115c",
          "sha256": "f533476c97cfa1988085cf3abd9a7ef9c70a5b9002cbb60f2021525375a1d56a",
          "sha1": "2a3c29075227c612afec138c6b3768c2c56ed6a4",
          "md5": "866865851b8e65ee11665fe3741c068e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "geniesdk-1.1.1.aar",
          "url": "geniesdk-1.1.1.aar",
          "size": 92144,
          "sha512": "2dc09e21e13ab10780f93327b8500997796108fc32a53ebe6ecc7356a962e2d4527c23501d93dfc27a00fafd7edfd52e5d3eb3359f6ac0c4207b077fb13e115c",
          "sha256": "f533476c97cfa1988085cf3abd9a7ef9c70a5b9002cbb60f2021525375a1d56a",
          "sha1": "2a3c29075227c612afec138c6b3768c2c56ed6a4",
          "md5": "866865851b8e65ee11665fe3741c068e"
        }
      ]
    }
  ]
}
